script-lang-basic/5/school/config/routes.rb
Rails.application.routes.draw do
  get 'courses/:id' => 'courses#show'
  get 'courses' => 'courses#showall'
  get 'faculties/:id' => 'faculties#show'
  resources :students
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

script-lang-basic/5/school/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

script-lang-basic/5/school/app/models/course.rb
class Course < ApplicationRecord
end

script-lang-basic/5/school/app/models/faculty.rb
class Faculty < ApplicationRecord
    has_many :students
end

script-lang-basic/5/school/app/models/student.rb
class Student < ApplicationRecord
    belongs_to :faculty
end

script-lang-basic/5/school/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

script-lang-basic/5/school/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.find(params[:id])
  end

  def showall
    @courses = Course.all
  end
end

script-lang-basic/5/school/app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def show
    @faculty = Faculty.find(params[:id])
    @students = @faculty.students
  end
end

script-lang-basic/5/school/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :faculty_id)
    end
end

script-lang-basic/5/school/app/helpers/application_helper.rb
module ApplicationHelper
end

script-lang-basic/5/school/app/helpers/courses_helper.rb
module CoursesHelper
end

script-lang-basic/5/school/app/helpers/faculties_helper.rb
module FacultiesHelper
end

script-lang-basic/5/school/app/helpers/students_helper.rb
module StudentsHelper
end

script-lang-basic/5/school/app/views/courses/show.html.erb
<h1>Courses#show</h1>


<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Credit</th>
            <th>Compulsory</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td><%= @course.id %></td>
                <td><%= @course.name %></td>
                <td><%= @course.credit %></td>
                <td><%= @course.compulsory %></td>
            </tr>
    </tbody>
</table>

script-lang-basic/5/school/app/views/courses/showall.html.erb
<h1>Courses#showall</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Detail</th>
        </tr>
    </thead>
    <tbody>
        <% @courses.each do |c| %>
            <tr>
                <td><%= c.id %></td>
                <td><%= c.name %></td>
                <td><a href="/courses/<%= c.id %>">link</a></td>
            </tr>
        <% end %>
    </tbody>
</table>

script-lang-basic/5/school/app/views/faculties/show.html.erb
<h1>Faculties#show</h1>
<p><b><%= @faculty.name %></b></p>


<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |s| %>
            <tr>
                <td><%= s.id %></td>
                <td><%= s.name %></td>
            </tr>
        <% end %>
    </tbody>
</table>

script-lang-basic/5/school/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>School</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  
    <%# SFC Logo %>
    <%= image_tag "https://www.sfc.keio.ac.jp/img/logo.png", class: "block" %>

    <style>
      .block {
        display: block;
      }
    </style>
  </body>
</html>

script-lang-basic/5/school/app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :faculty_id %>
    <%= form.number_field :faculty_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

script-lang-basic/5/school/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

script-lang-basic/5/school/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Faculty</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.faculty.name %></td>
        <td><%= student.grade %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

script-lang-basic/5/school/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

script-lang-basic/5/school/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @student.faculty_id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>